Fix py2 v py3 diff in "incorrect num args" error handling for subcmds
Before:

$ PYTHONPATH=`pwd`/lib python2 melange.py startproject
startproject startproject: takes exactly 1 argument (0 given)
Try 'startproject help startproject' for info.

$ PYTHONPATH=`pwd`/lib python3 melange.py startproject
Traceback (most recent call last):
  File "melange.py", line 18, in <module>
    main()
  File "melange.py", line 16, in main
    sys.exit(admin.main())
  File "/Users/trentm/tm/cmdln/lib/cmdln.py", line 264, in main
    return self.cmd(args)
  File "/Users/trentm/tm/cmdln/lib/cmdln.py", line 287, in cmd
    retval = self.onecmd(argv)
  File "/Users/trentm/tm/cmdln/lib/cmdln.py", line 425, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/Users/trentm/tm/cmdln/lib/cmdln.py", line 1126, in _dispatch_cmd
    return handler(argv[0], opts, *args)
TypeError: do_startproject() missing 1 required positional argument: 'projectname'

See #36.